class_name ApothecaryLayout
extends RefCounted
## GENERATED by tools/export_room_background.py from Room Background.pdf: do not edit by hand.
## Every layer: its picture (assets/ui/new/room/<file>.png), its top-left in the scene (1918 x 1080 px, centred on the 1920 stage) and its z.

const SCENE_W := 1918
const LAYERS := [
	{"id": "bg", "file": "apothecary_bg", "x": 0, "y": 1, "z": 0, "w": 1918, "h": 1080},
	{"id": "forest", "file": "apothecary_forest", "x": 0, "y": 1, "z": 1619, "w": 1918, "h": 805},
	{"id": "decor_forest", "file": "apothecary_decor_forest", "x": 45, "y": 430, "z": 1619.5, "w": 1630, "h": 622},
	{"id": "merchant", "file": "apothecary_merchant", "x": 277, "y": 499, "z": 2244.5, "w": 511, "h": 519},
	{"id": "cart", "file": "apothecary_cart", "x": 701, "y": 104, "z": 2472, "w": 835, "h": 786},
	{"id": "decor_cart", "file": "apothecary_decor_cart", "x": 1537, "y": 777, "z": 2472.5, "w": 316, "h": 304},
	{"id": "sign", "file": "apothecary_sign", "x": 1542, "y": 782, "z": 2739.5, "w": 307, "h": 299},
	{"id": "decor_sign", "file": "apothecary_decor_sign", "x": 1109, "y": 470, "z": 2740.0, "w": 441, "h": 518},
	{"id": "plate", "file": "apothecary_plate", "x": 697, "y": 818, "z": 4076.5, "w": 522, "h": 173},
]
const PLATE := {"x": 697, "y": 818, "w": 522, "h": 173, "z": 4076.5}
const LIGHTS := {
	"lantern": {"x": 753, "y": 378, "r": 137, "color": Color(0.979, 0.825, 0.465)},
	"crystal": {"x": 318, "y": 545, "r": 72, "color": Color(0.933, 0.361, 0.192)},
}
