class_name CampfireLayout
extends RefCounted
## GENERATED by tools/export_fight_ui.py from the campfire pages of Fight UI.pdf: do not edit by hand.
## Every layer: its picture (assets/ui/new/campfire/<file>.png), its top-left on the 1920 x 1080 stage, and its z (the stacking order).

const LAYERS := [
	{"id": "bg", "file": "campfire_bg", "x": -8, "y": 1, "z": 0, "w": 1936, "h": 1080},
	{"id": "forest", "file": "campfire_forest", "x": -6, "y": 1, "z": 379.5, "w": 1936, "h": 1080},
	{"id": "decor_forest", "file": "campfire_decor_forest", "x": 94, "y": 321, "z": 380.0, "w": 1755, "h": 677},
	{"id": "rest", "file": "campfire_rest", "x": 1139, "y": 265, "z": 590.5, "w": 760, "h": 732},
	{"id": "decor_rest", "file": "campfire_decor_rest", "x": 1332, "y": 684, "z": 591.0, "w": 125, "h": 140},
	{"id": "smoke", "file": "campfire_smoke", "x": 853, "y": 185, "z": 671, "w": 193, "h": 452},
	{"id": "decor_smoke", "file": "campfire_decor_smoke", "x": 516, "y": 594, "z": 671.5, "w": 500, "h": 106},
	{"id": "resin", "file": "campfire_resin", "x": 677, "y": 430, "z": 709.5, "w": 511, "h": 477},
	{"id": "fire_small", "file": "campfire_fire_small", "x": 843, "y": 688, "z": 715, "w": 174, "h": 164},
	{"id": "decor_fire_small", "file": "campfire_decor_fire_small", "x": 317, "y": 762, "z": 715.5, "w": 749, "h": 170},
	{"id": "fuse", "file": "campfire_fuse", "x": 315, "y": 664, "z": 766, "w": 374, "h": 268},
	{"id": "decor_fuse", "file": "campfire_decor_fuse", "x": 321, "y": 783, "z": 766.5, "w": 766, "h": 123},
	{"id": "fire_big", "file": "campfire_fire_big", "x": 838, "y": 646, "z": 799, "w": 181, "h": 217},
	{"id": "decor_fire_big", "file": "campfire_decor_fire_big", "x": 123, "y": 814, "z": 799.5, "w": 958, "h": 167},
	{"id": "sign_shadow", "file": "campfire_sign_shadow", "x": 115, "y": 986, "z": 1000.9, "w": 218, "h": 95},
	{"id": "sign_post", "file": "campfire_sign_post", "x": 115, "y": 824, "z": 1001, "w": 218, "h": 475},
	{"id": "sign_grass", "file": "campfire_sign_grass", "x": 47, "y": 965, "z": 1195.5, "w": 353, "h": 117},
]
const SIGN_TEXT := {"font": "iCielCadena", "size": 48, "color": Color(0.345, 0.196, 0.161), "cx": 227, "cy": 905}
const SIGN := {"delta": 231, "board_w": 207}
const INFO_TEXT := {"font": "SFUFuturaOblique", "size": 20, "color": Color(0.290, 0.157, 0.114), "cx": 226, "cy": 1034, "w": 215}
