class_name ChantLayout
extends RefCounted
## GENERATED by tools/export_circus_chant.py from Chant UI for Circus.pdf: do not edit by hand.
## Cirus theme. Every position is in px from the top-left of the Bag strip; the strip is 1100 px wide (S = 1.9097 px per PDF point).

const FRAME_CHANT := Vector2(1098, 117)  # the Chant strip picture's size
const FRAME_BAG := Vector2(935, 117)  # the Bag strip picture's size
const CAP := Vector2(73, 69)  # 9-slice margins of the strips: left, right
const TUBE_BACK := Vector2(865.1, 17.2)
const TUBE_GLASS := Vector2(859.4, 14.3)
const GEAR := Vector2(833.6, 24.3)  # top-left; turns twice for one turn of the crank
const GEAR_SIZE := Vector2(67, 67)
const PLATE := Vector2(827.2, 17.5)
const HANDLE := Vector2(841.5, 29.0)  # top-left of the handle at rest (pointing up)
const HANDLE_SIZE := Vector2(12, 36)
const HANDLE_PIVOT := Vector2(6.0, 30.0)  # inside the handle picture: the centre of its round bottom end
const AXIS_Y := 59.2  # the row the Essence roll along, from the strip's top
const REST_X := 105.0  # left edge of the leftmost resting Essence
const REST_END := 826.9  # the Essence rest left of this x (the crank plate)
const TUBE_HIDE_X := 1021.7  # right of this x the Essence are inside the machine, under the red block
const TUBE_RIGHT := 1100.0  # the tube's right end
